@startuml
title Diagrama de Classes - Fluxo de Cliente
skinparam classAttributeIconSize 0
skinparam linetype ortho

package "Models/Domains" {
    class Usuario {
        #id : int
        #email : str
        #senha : str
        #foto : str
    }

    class Cliente {
        +to_dict()
        +to_dict_with_password()
    }

    Usuario <|-- Cliente
}

package "Repositories" {
    class ClienteRepository {
        -db
        +criar()
        +listar()
    }
}

package "Services" {
    class SenhaService{
        +hash_senha()
        +verificar_senha()
    }


}

package "Managers" {
    class ClienteManager {
        +listar_clientes()
        +criar_cliente()
    }
}

package "Controllers" {
    class ClienteController {
        +_registrar_rotas()
    }
}

' Relacionamentos
ClienteController ..> ClienteManager : chama
ClienteManager ..> SenhaService: usa
ClienteManager --> ClienteRepository : chama
ClienteManager ..> Cliente : instancia
ClienteRepository ..> Cliente : armazena
@enduml
